# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request
jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-20.04
    env:
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: php_project_57
      DB_USERNAME: postgres
      DB_PASSWORD: password

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: php_project_57
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: make workflow
      - name: Start Web server
        run: make startNoWait
      - name: Run linter
        run: make lint
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        # NOTE: uncomment for using workflow
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/build/logs/clover.xml:clover
          debug: true
